db:
  url: "data/development/sounds.db"
server:
  port: "3001"
  cors:
    - "http://localhost:9000"
    - "http://localhost:9001"
data:
  path: "data/development"
  prefix: "sounds_dca"
auth:
  secret: "ks8tnQMCciUabiF2tBbs"
  username: "admin"
  password: "$2a$10$.Npl8RMzm0WFQXRMP9rofukT4b7vfK21yLZe7LekuwJ6omWUpPVsS"