botToken: abcde
dbUrl: /sounds_dca/sounds.db
botPrefix: $
botHelp: Help message
botPlaying: Playing something
botNotFound: Sound not found
soundDir: /
name: ExampleBot
applicationId: 1234567
soundCacheSize: 100
maxQueueSize: 6
env: development
logChannelId: 1234567